### PR TITLE
Login and SignUp with Google

### PR DESCRIPTION
**Pull request by KaroK365**
This PR refers to issue #19 

I have implement Login with google in Login Page and SignUp with google in SignUp page

### CODE REVIEW

**Comment by AvgBlank** [comment]
Hey man! Everything seems good!

**Comment by KaroK365** [comment]
Is there anything else i could work on??

**Comment by SHANip9** [comment]
it seems good .... add the gesture features it would give a real app version feel

**Comment by AvgBlank** [comment]
Sure! You could work on the gesture feature, but please do it in a new issue, it appears I've forgotten to lock this PR. Will do so after your acknowledgement.
@KaroK365

**Comment by KaroK365** [comment]
Yea you can lock the PR will look at new issues

**Pull request merged**
