### PR TITLE
Fix #15: Add feature to delete URL history 

### LINKED ISSUE #15: Enhancement: Delete URL Shortening History
This feature introduces the ability to _**delete URL shortening history**_, allowing users to manage their data more effectively. Users can now remove specific URL entries from their history or clear their entire shortening history as needed. This functionality is especially useful for maintaining privacy, reducing clutter, and keeping track of only relevant shortened URLs.

### USECASE OF THIS FEATURE

1. **Selective or Full Deletion**: Users can delete individual URL entries or clear the entire history with one action.
2. **Enhanced Privacy Control**: Offers users control over their data, supporting privacy and data management.
3. **Streamlined Interface**: Designed for easy access in the user interface to make history management quick and efficient.

image
_

> As there is no option for deleting the history

_

### PR DESCRIPTION
**Pull request by NOOBMASTER-08**
This merge request implements the "Delete URL Shortening History" feature, allowing users to manage their URL shortening history by deleting individual entries
Screenshot 2024-10-27 103659
Added a "Delete" button next to each URL entry in the Statistics, enabling users to delete specific entries.
Screenshot 2024-10-29 235727
"Fixes: #15 "

### CODE REVIEW

**Comment by AvgBlank** [comment]
Hey! After the delete button is pressed, could you add a confirmation "Are you sure you want to delete `URL to be Deleted`?".

**Comment by NOOBMASTER-08** [comment]
okay I'll add it

**Comment by NOOBMASTER-08** [comment]
I have added a confirmation "Are you sure you want to delete `**URL-to-be-Deleted**`?
Screenshot 2024-10-30 153739

**Comment by NOOBMASTER-08** [comment]
@AalokeCode Hey.....please review my PR and merge if you feel it good and appropriate . As today is the last day of OCTOBER  `**(deadline for HACKTOBERFEST)**`

**Comment by AalokeCode** [comment]
Hey! Alright lemme go through.

**Review by AalokeCode — APPROVED** [review]
Looks good! Thanks for your contribution

**Pull request merged**
