### PR TITLE
Fix #3 Containerized the application using Docker

### LINKED ISSUE #3: Enhancement: Containerize the application
Setting up this project requires the user to manually install Mongo DB, python & the python dependencies. This whole process can be automated using Docker. Assign this to me for Haktoberfest!

### PR DESCRIPTION
**Pull request by ubaidrmn**
This fixes #3 . I have also updated the readme file for instructions on how to setup the project using Docker. Please review this PR.

### CODE REVIEW

**Comment by ubaidrmn** [comment]
I feel like there is room for improvement in the readme file as some steps are being repeated in both manual installation & docker installation 🤔. But I'm not exactly sure. Need you to review this @AvgBlank @AalokeCode

**Comment by AalokeCode** [comment]
Hey! We will review the code and let you know.

**Comment by AvgBlank** [comment]
Hello! Yes, upon going through the README file, I am noticing redundancy between the locally cloning/locally cloning using docker. I think we could perhaps go for either one of the two, or just offer docker as another alternative to setting up the program. 
Let me know your thoughts.

**Comment by ubaidrmn** [comment]
> Hello! Yes, upon going through the README file, I am noticing redundancy between the locally cloning/locally cloning using docker. I think we could perhaps go for either one of the two, or just offer docker as another alternative to setting up the program. 
> Let me know your thoughts.

I think the users should be able to set it up both ways. If you think the instructions are clear enough then I guess it's not really a problem. Let me know if I should change anything.

**Pull request merged**
