### PR TITLE
Enhancement: Improve index.html

### PR DESCRIPTION
**Pull request by RishiAnand108**
Enhancements:
Responsive Design: Added max-w-xl and mx-auto to center and limit the width of the main container.

Improved Spacing and Font Sizes: Adjusted padding, margins, and font sizes for better readability.

Interactive Feature: Added a URL input field and a button to simulate URL shortening with a simple JavaScript function.

Responsive Buttons: Ensured buttons are full-width on small screens and auto-width on larger screens using w-full and sm:w-auto.

### CODE REVIEW

**Comment by RishiAnand108** [comment]
please approve the deployment and merge my pr request

**Comment by RishiAnand108** [comment]
1. Please can you merge and accept pr under hacktober label please sir do help

**Review by AalokeCode — CHANGES_REQUESTED** [review]
The shorten url button in index is of no use. Can you remove it?

**Comment by RishiAnand108** [comment]
i have done the required changes can you plese approve it

**Comment by AalokeCode** [comment]
Alright! give me 5 minutes and I'll merge

**Pull request merged**
