### PR TITLE
Fix #4: Create USER_GUIDE.md

### LINKED ISSUE #4: Documentation: Create a Comprehensive User Guide for the URL Shortener App
This issue is to create a comprehensive, user-friendly guide for the URL Shortener App. The guide will cover everything users need to know to get started, including how to shorten links, view their saved URLs, troubleshoot common issues, and understand link tracking.

Key Sections to Include:

Overview of the app’s purpose and benefits.
Step-by-step instructions for shortening a URL.
How to view, manage, and track shortened URLs.
Troubleshooting common issues.
Frequently Asked Questions (FAQ).
Pro tips for maximizing the app’s potential.
Contact and support options.
This user guide will make the app more accessible for new users and improve the overall user experience.

### PR DESCRIPTION
**Pull request by DidiNDexter**
This pull request introduces a new file, USER_GUIDE.md, which provides a complete, step-by-step guide for using the URL Shortener App. The guide covers essential topics, including:

Overview of the app and its main features
Instructions for shortening URLs
Managing and tracking saved URLs
Troubleshooting common issues
Frequently Asked Questions (FAQ)
Pro tips for getting the most out of the app
This addition aims to improve user experience by giving new and returning users a clear reference on how to navigate and utilize the app effectively. The guide is linked in the README for easy access.

### CODE REVIEW

**Review by AalokeCode — APPROVED** [review]
Looks good!

**Comment by AvgBlank** [comment]
Hello! I like the idea that you've proposed but, I am seeing a few mistakes (or rather unfilled information) that you could probably fix.
In the key benefits section, you've said "if available" for tracking clicks, which is available. 
The third section viewing shortened URLs, the app does support this feature, so remove the part that says, "If the app includes a user account feature". Click tracking again in the same.
And, for the FAQs, the second answer seems incorrect. As of right now, there is no way to not make a link be permanent.

Please make these changes

**Review by AvgBlank — COMMENTED** [review]
Hello! I like the idea that you've proposed but, I am seeing a few mistakes (or rather unfilled information) that you could probably fix.
In the key benefits section, you've said "if available" for tracking clicks, which is available.
The third section viewing shortened URLs, the app does support this feature, so remove the part that says, "If the app includes a user account feature". Click tracking again in the same.
And, for the FAQs, the second answer seems incorrect. As of right now, there is no way to not make a link be permanent.

Please make these changes

**Review by AvgBlank — CHANGES_REQUESTED** [review]
Hello! I like the idea that you've proposed but, I am seeing a few mistakes (or rather unfilled information) that you could probably fix.
In the key benefits section, you've said "if available" for tracking clicks, which is available.
The third section viewing shortened URLs, the app does support this feature, so remove the part that says, "If the app includes a user account feature". Click tracking again in the same.
And, for the FAQs, the second answer seems incorrect. As of right now, there is no way to not make a link be permanent.

Please make these changes

**Comment by DidiNDexter** [comment]
I have effected the changes @AvgBlank  @AalokeCode

**Comment by DidiNDexter** [comment]
Please if the changes are okay with you, accept the PR and add the hacktoberfest label @AalokeCode  @AvgBlank

**Comment by AalokeCode** [comment]
Alright! We will verify and let you know by tomorrow.

**Pull request merged**
